### ISSUE TITLE
Cannot find module 'electron'

### ISSUE THREAD

**Issue by dinuchiriacsonos** [geekuillaume/soundsync#10]
I'm trying to get SoundSync up and running on a headless raspberry pi.

1. The problem is that there is no documentation about where SoundSync and how or whether I can start it from the command line however it was straightforward to find it in services:
```
/opt/Soundsync/package_extra/systemd/default/files/etc/systemd/system/soundsync.service
```
2. When trying to start it from as a service there is no feedback in the console but when I check the status it says that the service is not running:
```
● soundsync.service - soundsync
   Loaded: loaded (/etc/systemd/system/soundsync.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-07-10 13:16:39 BST; 5min ago
  Process: 22591 ExecStart=/opt/Soundsync/soundsync --configDir /etc/soundsync (code=exited, status=1/FAILURE)
 Main PID: 22591 (code=exited, status=1/FAILURE)

Jul 10 13:16:39 rpi170 systemd[1]: soundsync.service: Service RestartSec=100ms expired, scheduling restart.
Jul 10 13:16:39 rpi170 systemd[1]: soundsync.service: Scheduled restart job, restart counter is at 5.
Jul 10 13:16:39 rpi170 systemd[1]: Stopped soundsync.
Jul 10 13:16:39 rpi170 systemd[1]: soundsync.service: Start request repeated too quickly.
Jul 10 13:16:39 rpi170 systemd[1]: soundsync.service: Failed with result 'exit-code'.
Jul 10 13:16:39 rpi170 systemd[1]: Failed to start soundsync.
```
3. So It looks like the service is crashing when trying to start the executable which actually complains about not being able to find electron:
```
pi@rpi170:~/SoundSync $ /opt/Soundsync/soundsync "--configDir" "/etc/soundsync"
internal/modules/cjs/loader.js:720
    throw err;
    ^

Error: Cannot find module 'electron'
Require stack:
- /opt/Soundsync/resources/app/utils/electronErrorHandler.js
- /opt/Soundsync/resources/app/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/opt/Soundsync/resources/app/utils/electronErrorHandler.js:6:36)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Soundsync/resources/app/utils/electronErrorHandler.js',
    '/opt/Soundsync/resources/app/index.js'
  ]
}
```

I successfully installed electron by the following documentation [here](https://www.electronjs.org/docs/tutorial/installation) however, the problem still persists.

**Comment by dinuchiriac** [comment]
Update:
It turns out I cannot import electron in `node` at all and that's because npm modules path is different than node `module.paths`.
Here is a quick fix for that, thanks to [stackoverflow](https://stackoverflow.com/questions/13465829/node-js-modules-path):
```
echo 'export NODE_PATH="'$(npm root -g)'"' >> ~/.bash_profile && . ~/.bash_profile
```
However,  taking in consideration that SoundSync is invoked by root,  we need to update root's `.bashrc` as well:
```
echo 'export NODE_PATH="'$(npm root -g)'"' >> /root/.bashrc
```
Now if you'll run node with root it starts:
```
sudo su
/opt/Soundsync/soundsync --configDir /etc/soundsync
```
However, it still crashes if I try to run it as a service: `sudo service soundsync start`

**Comment by geekuillaume** [comment]
Thanks for taking the time to help me with this. I changed something yesterday that broke this but I've just pushed the fix. Can you try again once the build is finished? (In around 30 minutes for ARM, this is slow :( )

**Comment by geekuillaume** [comment]
I've just tested it on a headless rPi and it works fine now. @dinuchiriacsonos can you test again and reopen the issue if this is still broken on your end?

**Comment by dinuchiriac** [comment]
Thanks for quick fix @geekuillaume 
I downloaded latest build from the latest `gh-actions`, works well, no issues anymore. Not sure about the release page build, has it been updated?

**Comment by geekuillaume** [comment]
@dinuchiriac for now I'm not updating the version number, instead I overwrite the assets off the release. I need to configure the auto updater for Electron (which has been one of the biggest reason I used Electron instead of another lighter method of distribution).
