### ISSUE TITLE
Cant install deb package on Raspbian, problem  with archieve

### ISSUE THREAD

**Issue by Miksier** [geekuillaume/soundsync#16]
Hi. ts a weird issue I think. I installed soundsync on Windows, and tried it also on my raspberry Pi 3B+ but sadly has problems with installing it more specifically with unpacking the package with any method. On windows the same package didnt have any problems with being opened by 7zip. Tried redownloading the file many times but nothing changed.

I've tried with apt-get, gdebi, tried unpacking it with tar and xz-utils with no success.
I've renamed it sound_2.deb so its easier to type..

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster

sudo apt install /home/pi/Downloads/sound_2.deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'soundsync' instead of '/home/pi/Downloads/sound_2.deb'
The following package was automatically installed and is no longer required:
  libreoffice-gtk2
Use 'sudo apt autoremove' to remove it.
The following NEW packages will be installed:
  soundsync
0 upgraded, 1 newly installed, 0 to remove and 355 not upgraded.
Need to get 0 B/55.9 MB of archives.
After this operation, 176 MB of additional disk space will be used.
Get:1 /home/pi/Downloads/sound_2.deb soundsync armhf 0.1.0 [55.9 MB]
(Reading database ... 141591 files and directories currently installed.)
Preparing to unpack /home/pi/Downloads/sound_2.deb ...
Unpacking soundsync (0.1.0) ...
dpkg-deb (subprocess): decompressing archive member: lzma error: compressed data is corrupt
dpkg-deb: error: <decompress> subprocess returned error exit status 2
dpkg: error processing archive /home/pi/Downloads/sound_2.deb (--unpack):
 cannot copy extracted data for './opt/Soundsync/icudtl.dat' to '/opt/Soundsync/icudtl.dat.dpkg-new': unexpected end of file or stream
Errors were encountered while processing:
 /home/pi/Downloads/sound_2.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

sudo gdebi sound_2.deb
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done

Plug virtual cables between any audio source and any speakers in your home
Do you want to install the software package? [y/N]:y
/usr/bin/gdebi:113: FutureWarning: Possible nested set at position 1
  c = findall("[[(](\S+)/\S+[])]", msg)[0].lower()
(Reading database ... 141591 files and directories currently installed.)
Preparing to unpack sound_2.deb ...
Unpacking soundsync (0.1.0) ...
dpkg-deb (subprocess): decompressing archive member: lzma error: compressed data is corrupt
dpkg-deb: error: <decompress> subprocess returned error exit status 2
dpkg: error processing archive sound_2.deb (--install):
 cannot copy extracted data for './opt/Soundsync/icudtl.dat' to '/opt/Soundsync/icudtl.dat.dpkg-new': unexpected end of file or stream
Processing triggers for gnome-menus (3.31.4-3) ...
Processing triggers for desktop-file-utils (0.23-4) ...
Processing triggers for mime-support (3.62) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 sound_2.deb

tar -xvf data.tar.xz (i was able to unpack the .deb package)
./
./usr/
./usr/share/
./usr/share/applications/
./usr/share/applications/soundsync.desktop
./usr/share/doc/
./usr/share/doc/soundsync/
./usr/share/doc/soundsync/changelog.gz
./usr/share/icons/
./usr/share/icons/hicolor/
./usr/share/icons/hicolor/0x0/
./usr/share/icons/hicolor/0x0/apps/
./usr/share/icons/hicolor/0x0/apps/soundsync.png
./opt/
./opt/Soundsync/
./opt/Soundsync/natives_blob.bin
./opt/Soundsync/resources/
./opt/Soundsync/resources/res/
./opt/Soundsync/resources/res/logo_small.png
./opt/Soundsync/resources/res/logo_only.png
./opt/Soundsync/resources/res/logo.svg
./opt/Soundsync/resources/res/doc/
./opt/Soundsync/resources/res/doc/windows.md
./opt/Soundsync/resources/res/doc/raspberrypi.md
./opt/Soundsync/resources/res/logo_transparent.png
./opt/Soundsync/resources/res/logo_only.svg
./opt/Soundsync/resources/res/screenshot_menu.png
xz: (stdin): Compressed data is corrupt
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

**Comment by geekuillaume** [comment]
I just tried again on two of my RaspberryPi and it worked fine. Your problem is most likely caused by a corruption during the package download. Can you try downloading it again? I've also added instruction in the Readme about installing Soundsync on a headless Raspberry Pi: https://github.com/geekuillaume/soundsync#faq

**Comment by Miksier** [comment]
@geekuillaume 
Thanks for the answer. Will try again, to infinity and beyond! And good to see a FAQ with service, cool!

**Comment by Miksier** [comment]
I hate it when I do something 10 times, someone comes and tells me to do it again and now it works.
