### ISSUE TITLE
Controller keeps refreshing on MacOS

### ISSUE THREAD

**Issue by totti4ever** [geekuillaume/soundsync#21]
It loads the available speakers and sources and then just starts over again - not usable.

I already accepted cookies and disabled ublock origin - any other Ideas?

I'm on Chrome 84

**Comment by geekuillaume** [comment]
I cannot seem to reproduce this error. Can you look at Chrome Developer console and sends me what's shown?

**Comment by geekuillaume** [comment]
No response, I'm closing this. Feel free to reopen if you still experience this issue.
