### ISSUE TITLE
Application is not starting unless autoDetectAudioDevices is false

### ISSUE THREAD

**Issue by ThisIsAreku** [geekuillaume/soundsync#25]
OS: Windows 10 2004 (19041.450)
App version: soundsync-0.3.3-dev.exe

When using the default config of true, the application is stuck at `soundsync:sourcesSinksManager Detecting local audio devices`.
This line never return and halt the process
https://github.com/geekuillaume/soundsync/blob/b54c94c9d09cd1798718e4c1d34ed777ff8b7801/src/audio/audio_sources_sinks_manager.ts#L63

I was not able to catch any error, and the issue seems to lay inside the node-audioworklet native code

**Comment by geekuillaume** [comment]
I fixed this with the help of @ThisIsAreku in the last version of node-audioworklet. Soundsync has been updated to use the last version. Thanks again :)
