### ISSUE TITLE
connections to .local

### ISSUE THREAD

**Issue by gingerlime** [geekuillaume/soundsync#44]
It doesn't seem to affect functionality, but I'm seeing some connections to .local addresses which fail, as well as external connections to sslip.io that fail for other reasons... Was wondering if this info is useful to report :) 

![Screenshot 2020-10-11 at 09 26 27](https://user-images.githubusercontent.com/524274/95672828-192f3b80-0ba4-11eb-837b-e34c7f2f782f.png)

![Screenshot 2020-10-11 at 09 28 42](https://user-images.githubusercontent.com/524274/95672838-2d733880-0ba4-11eb-9b14-d306a1a90598.png)

Thanks for creating Soundsync, it looks amazing!

**Comment by geekuillaume** [comment]
The sslip.io and .local requests are two methods to initiate the WebRTC connection from a secure endpoint (https://soundsync.app) to a unsecure IP (the local IP of the Soundsync device). It need to pass a UUID to the other Soundsync instance. As it's not possible to have a certificate for a local IP address, the requests fails but they serve their purpose as the request is detected by the soundsync instance and the UUID is received.

**Comment by gingerlime** [comment]
Thanks for explaining. I appreciate it.
