### ISSUE TITLE
Missing "Web Page Output" option in Firefox 81

### ISSUE THREAD

**Issue by balaji-dutt** [geekuillaume/soundsync#48]
I notice that when I load the Controller page in Firefox 81, my standard audio devices are visible however the "Web Page Output" option that appears with Chrome is missing in Firefox. 

- **Firefox 81.0.2**:

![Screenshot_2020-10-19 Soundsync](https://user-images.githubusercontent.com/3147070/96442686-1be1fe80-123e-11eb-8e88-4900c6934877.png)

- **Chrome Version 88.0.4292.2**:

![19-10-2020 7-06-49 PM](https://user-images.githubusercontent.com/3147070/96442803-46cc5280-123e-11eb-9ddc-a088e5cd93d2.png)

I can see the following error messages in the Developer Console when I load the controller page:

````
Some cookies are misusing the recommended “SameSite“ attribute 2
Some cookies are misusing the recommended “SameSite“ attribute 5
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://soundsync.app/api/ip_registry/peers. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
WebRTC: ICE failed, add a TURN server and see about:webrtc for more details
````

- Other Version Info:
  - Soundsync v0.4.4

**Comment by geekuillaume** [comment]
I've tested on soundsync.app with Firefox 81 and it's working properly. Can you try executing this in the developer console `typeof AudioContext === 'function'` and `typeof AudioWorkletNode === 'function'` ? Both should return true.

**Comment by balaji-dutt** [comment]
Hi @geekuillaume 

`typeof AudioContext === 'function'` Returned `true` but `typeof AudioWorkletNode === 'function` returned false. 

I have added special permissions to the site to Autoplay Audio and Video but that does not change the return value for `typeof AudioWorkletNode`

**Comment by geekuillaume** [comment]
Are you running the webui from https://soundsync.app/ or from a local ip address? AudioWorkletNode requires a secure context to run (HTTPS).

**Comment by balaji-dutt** [comment]
@geekuillaume Interesting! Using https://soundsync.app/controller with WebRTC disabled but Enhanced Tracking protection enabled in Firefox works - I can see the Web Page Output option. However, in Chrome even with the local IP address I can see the Web Page Output option. 

Any thoughts on why local URL's work with Chrome but not Firefox? Happy to close the issue if local URL's are not officially supported.

**Comment by geekuillaume** [comment]
I've seen some weird behaviors with Firefox and local URL, it seems like they are applying more protection when running in an HTTP context. I'm going to add a message in the "Add sink" popup when the Web page output is unavailable to make it more obvious.

**Comment by geekuillaume** [comment]
Message added in https://github.com/geekuillaume/soundsync/commit/d90814536940c12de92079c4b96a89a2c3f734af. I'm closing this issue. Feel free to reopen if you have a question.
