### ISSUE TITLE
Can't Add a Spotify Player

### ISSUE THREAD

**Issue by LostSoulfly** [geekuillaume/soundsync#5]
On Windows 10 when I click ``ADD A SPOTIFY PLAYER``, leave everything blank except selecting my Windows PC as the Device and click ``ADD A SPOTIFY PLAYER``, the soundsync executable seems to crash and the tray icon disappears. After restarting it, the same thing happens. When I remove the Spotify entry from the config.json it runs fine again. This also happens when specifying a Spotify account. I've also tested it on two different Windows 10 machines with the same results.

There is a ``librespot`` file in the Config directory with CRC32 of ``7425098E`` and it is 7241216 bytes. It does not appear to be a Windows compatible library file.

**Comment by geekuillaume** [comment]
I found the error, I was naming the file `librespot` and trying to execute it but on Windows, the file needs to ends with `.exe` to be executable. I've pushed an update, can you reinstall Soundsync with the last executable (I didn't change the version number) and try again?

**Comment by LostSoulfly** [comment]
Thanks, that seems to have resolved it!

**Comment by LostSoulfly** [comment]
Awesome project. I haven't figured out how I want to use it yet, but I'll probably wait for windows native audio to be supported in the future. Thanks again!
