### ISSUE TITLE
Doesn't work with firefox

### ISSUE THREAD

**Issue by ohhai-kthxbai** [geekuillaume/soundsync#7]
Hello

I can't seem to get this to work with firefox (even in safe mode), I just get the spinning "connecting" graphic
Works (ish) in Chrome.

Thanks for sharing your work!

**Comment by geekuillaume** [comment]
Can you look at the developer console and post a screenshot of what's shown after activating the debug mode? ([instructions here](https://github.com/geekuillaume/soundsync#faq))

**Comment by geekuillaume** [comment]
@ohhai-kthxbai Any news? Without a response in 15 days I'll close this issue.

**Comment by geekuillaume** [comment]
No response, I'm closing. Feel free to reopen this issue if you still encounter this problem.
